window.terminos = [
	{
		title: 'Política de Privacidad',
		content: [
			{className: 'subtitle centered', text: 'AVISO DE PRIVACIDAD'},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Conforme a lo establecido en la Ley N° 29733, Ley de Protección de Datos Personales, el Decreto Supremo N° 003-2013-JUS, por el que se aprueba su Reglamento, se informa a El USUARIO y USUARIOS, que sean personas jurídicas y naturales, que sus datos personales serán tratados por LA MESA DE DINERO, conforme se detalla en este apartado.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `La información que se recopila. - LA MESA DE DINERO recopila la siguiente información del USUARIO y EMPRESA AUTORIZADA:`}},
			{className: 'numbered', num: '', content: {className: 'parragraph', text: `a) Datos personales proporcionados por El USUARIO al momento de registrarse y crearse una cuenta. Los datos que se requieren pueden ser de manera enunciativa, pero no limitativa, su nombre, apellidos, número de DNI, fecha de nacimiento, número de celular, dirección de correo electrónico, datos de representante legal y accionistas, declaración de origen de los fondos, dirección de domicilio (en adelante, los “Datos Personales”).`}},
			{className: 'numbered', num: '', content: {className: 'parragraph', text: `b) Información que se recolecta cuando El USUARIO utiliza la Plataforma, entre la que se incluye: (i) fecha y hora en la que el USUARIO solicita el servicio; (ii) historial de solicitudes de servicio que El USUARIO haya solicitado, a través de la Plataforma; (iii) Direcciones IP; (iv) Información sobre aspectos operativos de la Plataforma, como análisis y estadísticas de navegación, tráfico, entre otros (en adelante, la “Información de Uso”).`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Sobre el Banco de Datos de LA MESA DE DINERO. - Los Datos Personales y la Información de Uso serán incorporados a un banco de datos de titularidad de LA MESA DE DINERO. El USUARIO da su consentimiento expreso para la inclusión de su información en dicho banco de datos.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Uso de los Datos Personales. – Los Datos Personales y la Información de Uso serán tratadas con las siguientes finalidades:`}},
			{className: 'numbered', num: '(i)', content: {className: 'parragraph', text: `Atender el registro de El USUARIO y brindar soporte técnico.`}},
			{className: 'numbered', num: '(ii)', content: {className: 'parragraph', text: `Verificar y validar la identidad de El USUARIO.`}},
			{className: 'numbered', num: '(iii)', content: {className: 'parragraph', text: `Elaborar estudios estadísticos y/o analíticos sobre la operatividad y navegabilidad de la Plataforma.`}},
			{className: 'numbered', num: '(iv)', content: {className: 'parragraph', text: `Elaborar estudios estadísticos y/o analíticos sobre el servicio que brinda La Mesa de Dinero.`}},
			{className: 'numbered', num: '(v)', content: {className: 'parragraph', text: `Atender quejas, reclamos o sugerencias de El USUARIO y USUARIOS.`}},
			{className: 'numbered', num: '(vi)', content: {className: 'parragraph', text: `Enviarle comunicaciones y notificaciones de La Mesa de Dinero.`}},
			{className: 'numbered', num: '(vii)', content: {className: 'parragraph', text: `Ceder o compartir la Información de El USUARIO con proveedores o socios de LA MESA DE DINERO para permitir la ejecución de los servicios contratados por El USUARIO, sin violar los derechos de confidencialidad.`}},
			{className: 'numbered', num: '(viii)', content: {className: 'parragraph', text: `Transferir la Información de El USUARIO a empresas que brinden servicios basado en infraestructura en la nube en el extranjero, a fin de poder alojar y almacenar la Información de El USUARIO. Ello en la medida que resulta indispensable para poder brindarle el servicio contratado.`}},
			{className: 'numbered', num: '(ix)', content: {className: 'parragraph', text: `Usarlas para facilitar a El USUARIO al registro a futuras plataformas asociadas a la empresa LA MESA DE DINERO.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `El USUARIO manifiesta expresamente que ha sido debidamente informado de todas las finalidades antes mencionadas. Asimismo, a través de la aceptación del presente Aviso de Privacidad, autoriza y otorga su consentimiento, de manera previa, libre, expresa e inequívoca y gratuita, para el tratamiento de su información, de conformidad con las finalidades antes descritas. Sin perjuicio de lo anterior, reconoce y acepta que cualquier tratamiento de su información que sea necesaria para la ejecución de la relación contractual no requieren de su consentimiento.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Derechos de El USUARIO. - Se pone en conocimiento que los derechos de acceso, información, actualización, rectificación, inclusión, supresión o cancelación y oposición de sus Datos Personales se podrán ejercer mediante petición dirigida a1: Sin perjuicio de lo anterior, LA MESA DE DINERO podrá conservar determinada información a fin de que sirva de prueba ante una eventual reclamación contra nuestra empresa por responsabilidades derivadas del tratamiento de dicha información.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Modificaciones del Aviso de Privacidad. – La Mesa de Dinero se reserva expresamente el derecho a modificar, actualizar o completar en cualquier momento el presente Aviso de Privacidad. Cualquier modificación o actualización será inmediatamente publicada en la Plataforma y se le solicitará su aceptación y consentimiento nuevamente.`}}
		]
	},
	{
		title: 'Política de Privacidad',
		content: [
			{className: 'subtitile centered', text: 'CONFIDENCIALIDAD'},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `LA MESA DE DINERO se abstendrá de divulgar, publicar o comunicar a terceros cualquier información que conozca en virtud de la ejecución del presente Contrato. Toda información que reciba LA MESA DE DINERO se considera privilegiada y confidencial, por lo que divulgarla o transmitirla a terceros puede lesionar los intereses de El USUARIO. En consecuencia, LA MESA DE DINERO se obliga a guardar confidencialidad sobre los datos, especificaciones, estados financieros, valores o cualquier información que El USUARIO le proporcionen en relación con este Contrato, comprometiéndose además a no ponerla en manos ni a disposición de terceras personas.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Asimismo, LA MESA DE DINERO adoptará las medidas de seguridad necesarias para garantizar la protección de la información de El USUARIO para evitar su alteración, pérdida, tratamiento y/o acceso no autorizado, habida cuenta del estado de la técnica, la naturaleza de los datos almacenados y los riesgos a que están expuestos. En este sentido, LA MESA DE DINERO usará los estándares de la industria en materia de protección de la confidencialidad de la información de El USUARIO.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Las obligaciones de LA MESA DE DINERO con respecto a la información confidencial no se aplicarán a aquella información que (i) esté o vaya a estar disponibles al público, (ii) que LA MESA DE DINERO reciba legítimamente de terceros sin obligaciones de confidencialidad, (iii) que LA MESA DE DINERO pueda demostrar a satisfacción que fueron desarrolladas independientemente, o (iv) que El USUARIO autoricen a LA MESA DE DINERO su difusión. Sobre este último punto, autoriza expresamente a LA MESA DE DINERO a difundir información que le sirva a la Entidad Fiduciaria para dar cumplimiento a sus obligaciones como sujeto obligado ante la UIF, de conformidad con la Ley UIF, su Reglamento y normas complementarias.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Por otro lado, la excepción de confidencialidad también aplica en los siguientes casos: (i) solicitudes de información de autoridades públicas en ejercicio de sus funciones y el ámbito de sus competencias; (ii) solicitudes de información en virtud de órdenes judiciales; y, (iii) solicitudes de información en virtud de disposiciones legales.`}},
			{className: 'parragraph top-bordered', text: `1 Se tiene que habilitar una dirección de correo electrónico o canal específico para que El USUARIO puedan ejercer los derechos ARCO de la Ley de Datos Personales.`}
		]
	},
	{
		title: 'Política de Privacidad',
		content: [
			{className: 'subtitle centered', text: 'PROPIEDAD INTELECTUAL'},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `LA MESA DE DINERO es propietaria de todo el contenido, incluyendo imágenes, gráficos, textos y todos los elementos de propiedad industrial que se encuentren en la Plataforma. En aquellos casos en que no sea el propietario, LA MESA DE DINERO cuenta con todas las licencias necesarias para su uso por parte de los titulares de dicho contenido o derechos de propiedad intelectual.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Se deben respetar los derechos de propiedad intelectual de titularidad de LA MESA DE DINERO y de terceros. Queda prohibida la reproducción, distribución, transformación o cualquier otra forma de utilización del contenido que se encuentre en la Plataforma, sin la autorización previa y expresa de LA MESA DE DINERO.`}},
			{className: 'subtitle centered', text: 'CESIÓN DE POSICIÓN CONTRACTUAL'},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `El USUARIO no podrá ceder este Contrato, sin el consentimiento de LA MESA DE DINERO.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `No obstante, este Contrato podrá ser cedido por LA MESA DE DINERO, en caso decida vender sus acciones a favor de cualquier tercero, la misma que (i) quedará obligada por el presente Contrato; y/o (ii) será el nuevo encargado del banco de datos que contenga los datos y el registro de su empresa.`}},
			{className: 'numbered', num: '°', content: {className: 'parragraph', text: `Luego de producida la cesión, LA MESA DE DINERO no tendrá ninguna responsabilidad con respecto de cualquier hecho que ocurra a partir de la fecha de la cesión.`}},
			{className: 'subtitle centered', text: 'LIBRO DE RECLAMACIONES'},
			{className: 'parragraph', text: `El Libro de Reclamaciones virtual de La Mesa de Dinero le permite registrar sus quejas o reclamos relacionados a los Servicios brindado, conforme a la Ley Nº 29571, Código de Protección y Defensa del Consumidor.`},
			{className: 'subtitle centered', text: 'LEY APLICABLE Y JURISDICCIÓN'},
			{className: 'parragraph', text: `En caso de discrepancia o controversia las partes se someten a la jurisdicción de los Jueces y Tribunales de la ciudad de Lima.`}
		]
	}
];